### ISSUE TITLE
Add Getting Started section to README.md file

### ISSUE THREAD

**Issue by mjza** [minaoar/library-version-wise-opinion-extration#18]
The installation document is, in my opinion, the most crucial step in utilizing or contributing to a project.

The prerequisites and installation procedures needed to operate this project are unknown to me.

It is missing and must be added to the README.md file.

**Comment by minaoar** [comment]
Thank you for reporting this. We will review this bug after implementing the containerization issue #15, as docker can be run in any machine the the required dependencies should be installed in the docker image. Thank you!

**Comment by minaoar** [comment]
We are going to add How to Get Started section in the readme file so that any new user can easily run the application.
