### ISSUE TITLE
Cannot use pwd in Windows OS

### ISSUE THREAD

**Issue by mjza** [minaoar/library-version-wise-opinion-extration#20]
> pip install pwd
> ERROR: Could not find a version that satisfies the requirement pwd (from versions: none)
> ERROR: No matching distribution found for pwd

Not possible to run your project in windows:
https://stackoverflow.com/questions/31463597/error-wihle-installing-pwd-module-on-windows

**Comment by minaoar** [comment]
Thank you for reporting pwd related issue in Windows. Since we will containerize this under issue #15, we will review this issue again after we have portable docker for the project.

**Comment by minaoar** [comment]
We removed the pwd import as it's not needed. Thanks.
